#!/usr/bin/env bash

set -euo pipefail

server_index=$(mktemp)
cleanup() {
    rm -f "$server_index"
}
trap cleanup EXIT

curl -fsL https://dev.app.engoo.com/api/servers -o "$server_index"

read_server_name_interactive() {
    jq -r 'keys[]' < "$server_index" | fzf
}

get_ssh_url() {
    local server_name=$1
    jq -r '.[$name].ssh_url' --arg name "$server_name" < "$server_index"
}

ssh_to_server() {
    local server_name="${1:-}"
    local server_ssh_url

    if [ ! "$server_name" ]; then
        server_name=$(read_server_name_interactive)
    fi

    server_ssh_url=$(get_ssh_url "$server_name")

    if [ "$server_ssh_url" = null ]; then
        echo "No ssh url found for server '$server_name'"
        exit 1
    fi

    ssh "$server_ssh_url"
}

print_server_url() {
    local server_name server_ssh_url
    server_name=$(read_server_name_interactive)
    get_ssh_url "$server_name"
}

if [ -t 1 ]; then
    ssh_to_server "$@"
else
    print_server_url
fi
